#!/bin/bash
#
# generate_test_data.sh — Regenerate all test INI files and reference outputs.
#
# This script recreates everything needed for the dmeff validation test suite:
#   1. Test INI files in class_dmeff/test_dmeff/ (for reference generation)
#   2. Test INI files in class_dmeff_uptodate/test_dmeff/ (for validation)
#   3. Reference output files in class_dmeff_uptodate/test_dmeff/reference/
#
# The reference outputs are generated by running the ORIGINAL dmeff
# implementation in class_dmeff/ (CLASS v2.9.4). These serve as the ground
# truth that the ported code in class_dmeff_uptodate/ is compared against.
#
# Prerequisites:
#   - The class_dmeff/ directory must exist with the original v2.9.4 source
#   - A C compiler (gcc/cc) must be available for building
#
# Usage (from the repository root):
#     bash class_dmeff_uptodate/test_dmeff/generate_test_data.sh
#
# The script is idempotent: running it again overwrites everything cleanly.

set -e

# =====================================================================
# Determine directory layout
# =====================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
UPTODATE_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$UPTODATE_DIR")"
OLD_DIR="${REPO_ROOT}/class_dmeff"

echo "============================================"
echo "  dmeff Test Data Generator"
echo "============================================"
echo ""
echo "  Repository root:  ${REPO_ROOT}"
echo "  Old CLASS (v2.9.4): ${OLD_DIR}"
echo "  New CLASS (v3.3.4): ${UPTODATE_DIR}"
echo ""

if [ ! -d "$OLD_DIR" ]; then
    echo "ERROR: class_dmeff/ directory not found at ${OLD_DIR}"
    echo "This directory contains the original CLASS v2.9.4 with working dmeff"
    echo "and is needed to generate reference outputs."
    exit 1
fi

# =====================================================================
# Common cosmological parameters shared by all test cases
# =====================================================================
# These are defined once here so every INI file is consistent.

COMMON_COSMO="h = 0.6732
T_cmb = 2.7255
omega_b = 0.022032

A_s = 2.1e-9
n_s = 0.9660
tau_reio = 0.0543"

COMMON_OUTPUT="write background = yes
write thermodynamics = yes

thermodynamics_verbose = 1
background_verbose = 1"

# =====================================================================
# Function: write an INI file
# =====================================================================

write_ini() {
    local filepath="$1"
    local content="$2"
    mkdir -p "$(dirname "$filepath")"
    echo "$content" > "$filepath"
    echo "  Created: $filepath"
}

# =====================================================================
# Step 1: Create all test INI files
# =====================================================================

echo "--- Step 1: Creating test INI files ---"
echo ""

# For each test, we create the INI in both class_dmeff/test_dmeff/ and
# class_dmeff_uptodate/test_dmeff/. The files are identical (they use
# relative paths for the root= parameter).

# --- test_coulomb: Coulomb-like interaction (npow = -4) ---
COULOMB_INI="# Test case 1: Coulomb-like interaction (npow = -4)
# All dark matter is dmeff (omega_cdm = 0)

output = tCl,mPk,mTk
root = output/test_coulomb_

${COMMON_COSMO}
omega_cdm = 0.0
omega_dmeff = 0.12

m_dmeff = 0.01
N_dmeff = 1
sigma_dmeff = 1e-41
npow_dmeff = -4
dmeff_target = hydrogen
Vrel_dmeff = 29.0

${COMMON_OUTPUT}"

write_ini "${OLD_DIR}/test_dmeff/test_coulomb.ini" "$COULOMB_INI"
write_ini "${UPTODATE_DIR}/test_dmeff/test_coulomb.ini" "$COULOMB_INI"

# --- test_constant: Velocity-independent scattering (npow = 0) ---
CONSTANT_INI="# Test case 2: Velocity-independent scattering (npow = 0)
# All dark matter is dmeff (omega_cdm = 0)

output = tCl,mPk,mTk
root = output/test_constant_

${COMMON_COSMO}
omega_cdm = 0.0
omega_dmeff = 0.12

m_dmeff = 0.01
N_dmeff = 1
sigma_dmeff = 1e-30
npow_dmeff = 0
dmeff_target = baryon
Vrel_dmeff = 29.0

${COMMON_OUTPUT}"

write_ini "${OLD_DIR}/test_dmeff/test_constant.ini" "$CONSTANT_INI"
write_ini "${UPTODATE_DIR}/test_dmeff/test_constant.ini" "$CONSTANT_INI"

# --- test_electron: Electron target (npow = -2) ---
ELECTRON_INI="# Test case 3: Electron target (npow = -2)
# All dark matter is dmeff (omega_cdm = 0)

output = tCl,mPk,mTk
root = output/test_electron_

${COMMON_COSMO}
omega_cdm = 0.0
omega_dmeff = 0.12

m_dmeff = 0.01
N_dmeff = 1
sigma_dmeff = 1e-35
npow_dmeff = -2
dmeff_target = electron
Vrel_dmeff = 29.0

${COMMON_OUTPUT}"

write_ini "${OLD_DIR}/test_dmeff/test_electron.ini" "$ELECTRON_INI"
write_ini "${UPTODATE_DIR}/test_dmeff/test_electron.ini" "$ELECTRON_INI"

# --- test_mixed: Partial CDM replacement (half CDM, half dmeff) ---
MIXED_INI="# Test case 4: Partial replacement - half CDM, half dmeff
# Tests coexistence of CDM and dmeff

output = tCl,mPk,mTk
root = output/test_mixed_

${COMMON_COSMO}
omega_cdm = 0.06
omega_dmeff = 0.06

m_dmeff = 0.01
N_dmeff = 1
sigma_dmeff = 1e-41
npow_dmeff = -4
dmeff_target = hydrogen
Vrel_dmeff = 29.0

${COMMON_OUTPUT}"

write_ini "${OLD_DIR}/test_dmeff/test_mixed.ini" "$MIXED_INI"
write_ini "${UPTODATE_DIR}/test_dmeff/test_mixed.ini" "$MIXED_INI"

# --- test_multi: Multiple interaction terms (N_dmeff = 2) ---
MULTI_INI="# Test case 5: Multiple interaction terms (N_dmeff = 2)
# Tests array parameter handling with hydrogen + electron targets

output = tCl,mPk,mTk
root = output/test_multi_

${COMMON_COSMO}
omega_cdm = 0.0
omega_dmeff = 0.12

m_dmeff = 0.01
N_dmeff = 2
sigma_dmeff = 1e-41,1e-35
npow_dmeff = -4,-2
dmeff_target = hydrogen,electron
Vrel_dmeff = 29.0

${COMMON_OUTPUT}"

write_ini "${OLD_DIR}/test_dmeff/test_multi.ini" "$MULTI_INI"
write_ini "${UPTODATE_DIR}/test_dmeff/test_multi.ini" "$MULTI_INI"

# --- test_vanilla: Baseline (no dmeff) ---
VANILLA_INI="# Test case 6: Vanilla (no dmeff) - baseline comparison
# Confirms dmeff additions do not alter standard CLASS behavior

output = tCl,mPk,mTk
root = output/test_vanilla_

${COMMON_COSMO}
omega_cdm = 0.12

N_dmeff = 0

${COMMON_OUTPUT}"

write_ini "${OLD_DIR}/test_dmeff/test_vanilla.ini" "$VANILLA_INI"
write_ini "${UPTODATE_DIR}/test_dmeff/test_vanilla.ini" "$VANILLA_INI"

# --- test_coulomb_newtonian: Gauge consistency check ---
# Only needed in class_dmeff_uptodate (for validation, not reference generation)
COULOMB_NEWT_INI="# Test case: Coulomb-like interaction in Newtonian gauge
# Same as test_coulomb.ini but with gauge = newtonian
# Used for gauge consistency check

output = tCl,mPk,mTk
root = output/test_coulomb_newtonian_

${COMMON_COSMO}
omega_cdm = 0.0
omega_dmeff = 0.12

m_dmeff = 0.01
N_dmeff = 1
sigma_dmeff = 1e-41
npow_dmeff = -4
dmeff_target = hydrogen
Vrel_dmeff = 29.0

gauge = newtonian

${COMMON_OUTPUT}"

write_ini "${UPTODATE_DIR}/test_dmeff/test_coulomb_newtonian.ini" "$COULOMB_NEWT_INI"

echo ""

# =====================================================================
# Step 2: Build class_dmeff (the old v2.9.4 reference implementation)
# =====================================================================

echo "--- Step 2: Building class_dmeff (CLASS v2.9.4) ---"
echo ""

cd "$OLD_DIR"
if [ ! -x "./class" ]; then
    echo "  CLASS executable not found; building..."
    make -j4
    echo "  Build complete."
else
    echo "  CLASS executable already exists. To force rebuild: make clean && make"
fi

if [ ! -x "./class" ]; then
    echo "ERROR: Failed to build class_dmeff. Check compiler output above."
    exit 1
fi
echo ""

# =====================================================================
# Step 3: Run each test case in class_dmeff to generate reference outputs
# =====================================================================

echo "--- Step 3: Generating reference outputs from class_dmeff ---"
echo ""

TESTS="test_coulomb test_constant test_electron test_mixed test_multi test_vanilla"
SUFFIXES="background cl pk thermodynamics tk"

cd "$OLD_DIR"
mkdir -p output

for TEST in $TESTS; do
    echo "  Running ${TEST}..."

    # Delete stale output files
    rm -f output/${TEST}_*

    # Run CLASS
    if ! ./class test_dmeff/${TEST}.ini > /dev/null 2>&1; then
        echo "  ERROR: CLASS failed for ${TEST}. Run manually to see errors:"
        echo "    cd ${OLD_DIR} && ./class test_dmeff/${TEST}.ini"
        exit 1
    fi

    # Verify output files were created
    FILE_COUNT=0
    for SUFFIX in $SUFFIXES; do
        if [ -s "output/${TEST}_${SUFFIX}.dat" ]; then
            FILE_COUNT=$((FILE_COUNT + 1))
        else
            echo "  WARNING: output/${TEST}_${SUFFIX}.dat missing or empty"
        fi
    done
    echo "    Generated ${FILE_COUNT}/5 output files"
done

echo ""

# =====================================================================
# Step 4: Copy reference outputs to class_dmeff_uptodate/test_dmeff/reference/
# =====================================================================

echo "--- Step 4: Copying reference outputs ---"
echo ""

REF_BASE="${UPTODATE_DIR}/test_dmeff/reference"

for TEST in $TESTS; do
    REF_DIR="${REF_BASE}/${TEST}"
    mkdir -p "$REF_DIR"

    COPIED=0
    for SUFFIX in $SUFFIXES; do
        SRC="output/${TEST}_${SUFFIX}.dat"
        DST="${REF_DIR}/${TEST}_${SUFFIX}.dat"
        if [ -s "$SRC" ]; then
            cp "$SRC" "$DST"
            COPIED=$((COPIED + 1))
        fi
    done
    echo "  ${TEST}: copied ${COPIED} files to reference/"
done

echo ""

# =====================================================================
# Summary
# =====================================================================

echo "============================================"
echo "  Generation Complete"
echo "============================================"
echo ""
echo "  INI files created:"
echo "    ${OLD_DIR}/test_dmeff/  (6 files)"
echo "    ${UPTODATE_DIR}/test_dmeff/  (7 files, includes Newtonian gauge)"
echo ""
echo "  Reference outputs:"
echo "    ${REF_BASE}/  (6 test dirs x 5 files = 30 .dat files)"
echo ""
echo "  To verify the port, from ${UPTODATE_DIR}/ run:"
echo "    make clean && make"
echo "    bash test_dmeff/run_all_tests.sh"
echo ""
